### ISSUE TITLE
Data Exercise Bug/Error

### ISSUE THREAD

**Issue by cfiller123** [laderast/RBootcamp#10]
**Describe the bug/error**
On chapter 4 question 2, it returns "NA" regardless of which multiple choice you select.

**Where did you see it?**
chapter 4 question 2

**Expected behavior**
i expected one answer to be correct another to be wrong.

**Additional context**
tried refreshing, reloading, etc but no change in error.

**Comment by laderast** [comment]
Thanks for catching this. I will fix and attribute you.

**Comment by laderast** [comment]
Resolved. See https://github.com/laderast/RBootcamp/commit/777975727b460157cf67bfe302652b59926b30c2
