### ISSUE TITLE
Data Exercise Bug/Error

### ISSUE THREAD

**Issue by CarlosPumar-debug** [laderast/RBootcamp#13]
**Describe the bug/error**
hi - I have the impression that variable names are being mixed up in one of the exercises.

**Where did you see it?**
Exercise 7 in chapter 4. 

**Expected behavior**
The assignment of the exercise says "gather() the measurements into a single column called time with a key called interventionStatus." However, in the code one finds: gather function includes key = measurementStatus. Hence, it seems to me that the variable name has to be changed from interventionStatus to measurementStatus in the assignment.

**Additional context**
Thank you SO much for making this helpful bootcamp available!

**Comment by laderast** [comment]
Thanks for catching this. I will fix this

**Comment by laderast** [comment]
Changed and fixed.
