### ISSUE TITLE
Integrating own binder container 

### ISSUE THREAD

**Issue by BarryDigby** [laderast/RBootcamp#26]
Hi Ted, I have a quick question I was hoping you could help with. 

I have imported your repository and can deploy it locally via `gatsby develop`. I've tweaked the `binder/` repository to contain an `environment.yml` file and have successfully built the container on binder.  

How can I integrate my own binder container and tell it to stop loading yours? 

Sorry for the noob question ^_^ and thanks for this awesome resource!

**Comment by laderast** [comment]
Hi Barry,

Honestly, it's been a while since I've worked with the binder containers for this workflow. There may be more help at Ines' repo, which this is derived from. https://github.com/ines/course-starter-r

Best,
Ted
