### ISSUE TITLE
Data Exercise Bug/Error

### ISSUE THREAD

**Issue by Qeldoq** [laderast/RBootcamp#34]
**Describe the bug/error**
Bad link for aesthetic mappings
(http://ggplot.yhathq.com/docs/geom_point.html)

**Where did you see it?**
Chapter 1, Exercise 4 (More about aes)

**Expected behavior**
N/A

**Additional context**
I was able to get the content at this link:
https://ggplot2.tidyverse.org/reference/geom_point.html

Christine Doyle
(who will be starting BSTA 525 next week)

**Comment by laderast** [comment]
Thanks for pointing this out. This has been fixed in the new version
