### ISSUE TITLE
Data Exercise Bug/Error

### ISSUE THREAD

**Issue by amundhb** [laderast/RBootcamp#6]
**Describe the bug/error**
Solution does not load ggplot2 and gives error: "Error in ggplot(augmented_data, aes(x = total_mercury, y = .fitted, color = fishmlwk, : could not find function "ggplot""

**Where did you see it?**
Chapter 5:13

**Expected behavior**
Code will run, ggplot will make plots

**Additional context**
Fixed by adding library(ggplot2) to code

**Comment by laderast** [comment]
Thanks for catching this! I will push a fix.

**Comment by laderast** [comment]
Fixed.

**Comment by jminnier** [comment]
Ah thanks @amundhb and @laderast!

**Comment by laderast** [comment]
@amundhb - I've added you as a contributor in the [readme.md](https://github.com/laderast/RBootcamp/blob/master/README.md) file.
