### ISSUE TITLE
Help with Netlify?

### ISSUE THREAD

**Issue by juliasilge** [laderast/RBootcamp#9]
Hello! 👋 I am working on getting [my course](https://github.com/juliasilge/supervised-ML-case-studies-course) up and running, and I am not having luck with Netlify right now. Can you share any details about what you did to get Netlify to build your site? Here is what I have right now:

<img width="880" alt="Screen Shot 2019-08-23 at 9 17 22 PM" src="https://user-images.githubusercontent.com/12505835/63631956-799f9a00-c5eb-11e9-891e-1d84f8d8fa29.png">

I tried out using the same version of node as you, I get an error like this in the build, where it fails when it starts to run `npm`:
```
9:05:47 PM: Build ready to start
9:05:49 PM: build-image version: 9e0f207a27642d0115b1ca97cd5e8cebbe492f63
9:05:49 PM: build-image tag: v3.3.2
9:05:49 PM: buildbot version: ef8d0929ed0baabafd8bbb7d0b021e1fc24180c0
9:05:49 PM: Fetching cached dependencies
9:05:50 PM: Starting to download cache of 255.0KB
9:05:50 PM: Finished downloading cache in 80.136123ms
9:05:50 PM: Starting to extract cache
9:05:50 PM: Failed to fetch cache, continuing with build
9:05:50 PM: Starting to prepare the repo for build
9:05:50 PM: No cached dependencies found. Cloning fresh repo
9:05:50 PM: git clone https://github.com/juliasilge/courses-case-studies-supervised-r
9:05:53 PM: Preparing Git Reference refs/heads/master
9:05:54 PM: Starting build script
9:05:54 PM: Installing dependencies
9:05:56 PM: Downloading and installing node v10.16.2...
9:05:56 PM: Downloading https://nodejs.org/dist/v10.16.2/node-v10.16.2-linux-x64.tar.xz...
9:05:57 PM: 
#######
9:05:57 PM:                                             10.9%
9:05:57 PM: 
##########################
9:05:57 PM: ############################                    75.1%
9:05:57 PM: 
####################
9:05:57 PM: #################################################### 100.0%
9:05:57 PM: Computing checksum with sha256sum
9:05:57 PM: Checksums matched!
9:06:01 PM: Now using node v10.16.2 (npm v6.9.0)
9:06:01 PM: Attempting ruby version 2.6.2, read from environment
9:06:03 PM: Using ruby version 2.6.2
9:06:03 PM: Using PHP version 5.6
9:06:03 PM: Started restoring cached go cache
9:06:03 PM: Finished restoring cached go cache
9:06:03 PM: unset GOOS;
9:06:03 PM: unset GOARCH;
9:06:03 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
9:06:03 PM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
9:06:03 PM: go version >&2;
9:06:03 PM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
9:06:03 PM: go version go1.12 linux/amd64
9:06:03 PM: Installing missing commands
9:06:03 PM: Verify run directory
9:06:03 PM: Executing user command: npm run build
9:06:04 PM: npm
9:06:04 PM: ERR! path /opt/build/repo/package.json
9:06:04 PM: npm ERR! code ENOENT
9:06:04 PM: npm ERR! errno -2
9:06:04 PM: npm ERR! syscall open
9:06:04 PM: npm
9:06:04 PM: ERR! enoent ENOENT: no such file or directory, open '/opt/build/repo/package.json'
9:06:04 PM: npm
9:06:04 PM: ERR! enoent
9:06:04 PM:  This is related to npm not being able to find a file.
9:06:04 PM: npm
9:06:04 PM:  ERR! enoent
9:06:04 PM: npm
9:06:04 PM:  ERR! A complete log of this run can be found in:
9:06:04 PM: npm
9:06:04 PM:  ERR!     /opt/buildhome/.npm/_logs/2019-08-24T03_06_04_398Z-debug.log
9:06:04 PM: Skipping functions preparation step: no functions directory set
9:06:04 PM: Caching artifacts
9:06:04 PM: Started saving pip cache
9:06:04 PM: Finished saving pip cache
9:06:04 PM: Started saving emacs cask dependencies
9:06:04 PM: Finished saving emacs cask dependencies
9:06:04 PM: Started saving maven dependencies
9:06:04 PM: Finished saving maven dependencies
9:06:04 PM: Started saving boot dependencies
9:06:04 PM: Finished saving boot dependencies
9:06:04 PM: Started saving go dependencies
9:06:04 PM: Finished saving go dependencies
9:06:08 PM: Error running command: Build script returned non-zero exit code: 254
9:06:08 PM: Failing build: Failed to build site
9:06:08 PM: failed during stage 'building site': Build script returned non-zero exit code: 254
9:06:08 PM: Finished processing build request in 18.558697282s
```

**Comment by laderast** [comment]
Hi @juliasilge - I don't remember any issues when I deployed with netlify. I'm attaching my latest build log

12:22:36 PM: Build ready to start
12:22:40 PM: build-image version: 9e0f207a27642d0115b1ca97cd5e8cebbe492f63
12:22:40 PM: build-image tag: v3.3.2
12:22:40 PM: buildbot version: ef8d0929ed0baabafd8bbb7d0b021e1fc24180c0
12:22:41 PM: Fetching cached dependencies
12:22:41 PM: Starting to download cache of 158.5MB
12:22:42 PM: Finished downloading cache in 1.217789098s
12:22:42 PM: Starting to extract cache
12:22:48 PM: Finished extracting cache in 6.22701662s
12:22:48 PM: Finished fetching cache in 7.52873052s
12:22:48 PM: Starting to prepare the repo for build
12:22:49 PM: Preparing Git Reference refs/heads/master
12:22:49 PM: Starting build script
12:22:49 PM: Installing dependencies
12:22:50 PM: Started restoring cached node version
12:22:53 PM: Finished restoring cached node version
12:22:53 PM: Downloading and installing node v10.16.2...
12:22:54 PM: Downloading https://nodejs.org/dist/v10.16.2/node-v10.16.2-linux-x64.tar.xz...
12:22:54 PM: 
#####
12:22:54 PM:   7.4%
12:22:54 PM: 
########################################################################
12:22:54 PM: 100.0%
12:22:54 PM: Computing checksum with sha256sum
12:22:54 PM: Checksums matched!
12:22:57 PM: Now using node v10.16.2 (npm v6.9.0)
12:22:58 PM: Attempting ruby version 2.6.2, read from environment
12:22:59 PM: Using ruby version 2.6.2
12:23:00 PM: Using PHP version 5.6
12:23:00 PM: Started restoring cached node modules
12:23:00 PM: Finished restoring cached node modules
12:23:00 PM: Installing NPM modules using NPM version 6.9.0
12:23:17 PM: npm
12:23:17 PM:  WARN ts-pnp@1.1.2 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
12:23:17 PM: npm
12:23:17 PM:  WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
12:23:17 PM: npm
12:23:17 PM:  WARN
12:23:17 PM: notsup
12:23:17 PM:  SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
12:23:19 PM: audited 29144 packages in 18.575s
12:23:19 PM: found 565 vulnerabilities (2 low, 2 moderate, 561 high)
12:23:19 PM:   run `npm audit fix` to fix them, or `npm audit` for details
12:23:20 PM: NPM modules installed
12:23:20 PM: Started restoring cached go cache
12:23:20 PM: Finished restoring cached go cache
12:23:20 PM: unset GOOS;
12:23:20 PM: unset GOARCH;
12:23:20 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
12:23:20 PM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
12:23:20 PM: go version >&2;
12:23:20 PM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
12:23:20 PM: go version go1.12 linux/amd64
12:23:20 PM: Installing missing commands
12:23:20 PM: Verify run directory
12:23:20 PM: Executing user command: gatsby build
12:23:23 PM: success open and validate gatsby-configs — 0.558 s
12:23:24 PM: success load plugins — 1.301 s
12:23:24 PM: success onPreInit — 0.007 s
12:23:24 PM: success delete html and css files from previous builds — 0.006 s
12:23:24 PM: success initialize cache — 0.010 s
12:23:24 PM: success copy gatsby files — 0.035 s
12:23:24 PM: success onPreBootstrap — 0.009 s
12:23:25 PM: success source and transform nodes — 0.716 s
12:23:26 PM: success building schema — 0.440 s
12:23:26 PM: success createPages — 0.062 s
12:23:26 PM: success createPagesStatefully — 0.026 s
12:23:26 PM: success onPreExtractQueries — 0.001 s
12:23:26 PM: success update schema — 0.027 s
12:23:26 PM: success extract queries from components — 0.236 s
12:23:26 PM: success write out requires — 0.005 s
12:23:26 PM: success write out redirect data — 0.001 s
12:23:26 PM: success Build manifest and related icons — 0.129 s
12:23:26 PM: success onPostBootstrap — 0.130 s
12:23:26 PM: info bootstrap finished - 6.116 s
12:23:26 PM: success run static queries — 0.039 s — 4/4 106.09 queries/second
12:24:51 PM: success Building production JavaScript and CSS bundles — 84.644 s
12:24:51 PM: success Rewriting compilation hashes — 0.001 s
12:24:51 PM: warning code block language not specified in markdown. applying generic code block
12:24:52 PM: success run page queries — 1.128 s — 7/7 6.21 queries/second
12:24:59 PM: success Building static HTML for pages — 6.536 s — 7/7 11.39 pages/second
12:24:59 PM: warning app-b9b24bc96df6e0a50d64.js is 2.22 MB, and won't be precached. Configure maximumFileSizeToCacheInBytes to change this limit.
12:24:59 PM: Generated public/sw.js, which will precache 7 files, totaling 257251 bytes.
12:24:59 PM: info Done building in 98.909 sec
12:24:59 PM: Skipping functions preparation step: no functions directory set
12:24:59 PM: Caching artifacts
12:24:59 PM: Started saving node modules
12:24:59 PM: Finished saving node modules
12:24:59 PM: Started saving pip cache
12:24:59 PM: Finished saving pip cache
12:24:59 PM: Started saving emacs cask dependencies
12:24:59 PM: Finished saving emacs cask dependencies
12:24:59 PM: Started saving maven dependencies
12:24:59 PM: Finished saving maven dependencies
12:24:59 PM: Started saving boot dependencies
12:24:59 PM: Finished saving boot dependencies
12:24:59 PM: Started saving go dependencies
12:24:59 PM: Finished saving go dependencies
12:25:03 PM: Build script success
12:25:03 PM: Starting to deploy site from 'public/'
12:25:03 PM: Creating deploy tree 
12:25:03 PM: 22 new files to upload
12:25:03 PM: 0 new functions to upload
12:25:04 PM: Starting post processing
12:25:05 PM: Post processing done
12:25:06 PM: Site is live
12:25:34 PM: Finished processing build request in 2m53.663772884s

**Comment by laderast** [comment]
@ines - @juliasilge is having problems deploying to netlify - any tips?

**Comment by laderast** [comment]
Also - I have gatsby build as my build command:

![Screen Shot 2019-08-24 at 8 32 34 AM](https://user-images.githubusercontent.com/3315629/63639573-e77aae80-c649-11e9-8605-9c92790694db.png)

**Comment by juliasilge** [comment]
Oh @laderast I was connecting to the wrong repo! 🙈 🙈 🙈 

This goes to show me I should not try to do so much on Friday nights at the end of a long week. Thank you so much for what you've done in helping get this framework working for R folks, and of course to @ines for so much wonderful work.

By the way, my ex-DataCamp course is **not launched** yet (Binder not yet working) so I have not yet announced it. You can [preview it here](https://supervised-ml-course.netlify.com).

**Comment by laderast** [comment]
No problem! I just want to see more instructors using @ines's repo.

**Comment by laderast** [comment]
And don't hesitate to reach out if you need help setting up the binder container. It took me a little bit to really wrap my head around it.
